# Generated by Django 3.1.7 on 2021-04-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210405_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('PR', 'In progress'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
    ]
