# Generated by Django 3.1.7 on 2021-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('IP', 'In progress'), ('CL', 'Closed'), ('IR', 'More info required')], default='OP', max_length=2),
        ),
    ]
