# Generated by Django 3.1.7 on 2021-04-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210405_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
