version: "3.3"
   
services:
  web:
    restart: always
    build: .
    command: /bin/sh -c /code/entrypoint.prod.sh
    volumes:
      - static_volume:/code/static
    expose:
      - 8005
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - reverse-proxy_proxynet

  nginx:
    restart: always
    image: nginx:latest
    hostname: bug-tracker-django.kristianms.com
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    expose:
      - 1347
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=bug-tracker-django.kristianms.com
      - VIRTUAL_PORT=1347
      - LETSENCRYPT_HOST=bug-tracker-django.kristianms.com
      - LETSENCRYPT_EMAIL=kmollerschmidt@gmail.com
      - url=https://bug-tracker-django.kristianms.com
    networks:
      - reverse-proxy_proxynet

  db:
    image: postgres:14
    restart: always
    volumes:
      - database_volume:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.prod
    user: postgres:postgres
    networks:
      - reverse-proxy_proxynet


  pgbackups:
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    user: postgres:postgres
    volumes:
      - ./backups:/backups:rw
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs --clean
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    networks:
      - reverse-proxy_proxynet
volumes:
  database_volume: {}
  static_volume: {}

networks:
  reverse-proxy_proxynet:
    external: true