# Generated by Django 3.1.7 on 2021-04-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('D', 'Developer'), ('A', 'Admin'), ('PM', 'Project Manager')], default='D', max_length=2),
        ),
    ]
