# Generated by Django 3.1.7 on 2021-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210408_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer'), (2, 'Admin'), (3, 'Project Manager')], default=1),
        ),
    ]
