# Generated by Django 3.1.13 on 2021-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210409_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Developer'), (2, 'Admin'), (3, 'Project Manager')], default=1, null=True),
        ),
    ]
