# Generated by Django 3.1.7 on 2021-04-15 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Info Required'), (3, 'In Progress'), (4, 'Closed')], default=1, null=True)),
                ('property_changed', models.IntegerField(choices=[(1, 'Status'), (2, 'Priority Change'), (3, 'Type'), (4, 'Developer'), (5, 'Title'), (6, 'Description'), (7, 'Deleted')])),
                ('old_value', models.CharField(max_length=300)),
                ('new_value', models.CharField(max_length=300)),
                ('changed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
