# Generated by Django 3.1.7 on 2021-04-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210415_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketevent',
            name='status',
        ),
    ]
