# Generated by Django 3.1.7 on 2021-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticketevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='new_value',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='old_value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
