# Generated by Django 3.1.7 on 2021-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210408_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'Closed'), (4, 'More info required')], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Feature request'), (2, 'Bug/Error'), (3, 'Other')], null=True),
        ),
    ]
