# Generated by Django 3.1.7 on 2021-04-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210410_0750'),
        ('tickets', '0005_auto_20210408_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='projects.project'),
        ),
    ]
