# Generated by Django 3.1.7 on 2021-04-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210415_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketevent',
            old_name='changed_at',
            new_name='created_at',
        ),
    ]
