# Generated by Django 3.1.12 on 2021-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Default ticket title', max_length=200, unique=True),
        ),
    ]
