# Generated by Django 3.1.7 on 2021-04-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20210410_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_property', models.PositiveSmallIntegerField(choices=[(1, 'StatusChange'), (2, 'PriorityChange'), (3, 'TypeChange'), (4, 'DeveloperChange'), (5, 'TitleChange'), (6, 'DescriptionChange')])),
                ('old_value', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
            ],
        ),
    ]
