# Generated by Django 3.1.7 on 2021-04-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20210411_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketevent',
            old_name='changed_property',
            new_name='property_changed',
        ),
    ]
