# Generated by Django 3.1.7 on 2021-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210411_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='property_changed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TicketCreated'), (2, 'StatusChange'), (3, 'PriorityChange'), (4, 'TypeChange'), (5, 'DeveloperChange'), (6, 'TitleChange'), (7, 'DescriptionChange')]),
        ),
    ]
