# Generated by Django 3.1.7 on 2021-04-11 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_auto_20210411_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='property_changed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TicketCreated'), (2, 'StatusChange'), (3, 'PriorityChange'), (4, 'TypeChange'), (5, 'DeveloperChange'), (6, 'TitleChange'), (7, 'DescriptionChange'), (8, 'TicketDeleted')]),
        ),
    ]
