# Generated by Django 3.1.7 on 2021-04-12 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0014_auto_20210411_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(default='Default ticket description', max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'Closed'), (4, 'More info required')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Ticket #', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Feature request'), (2, 'Bug/Error'), (3, 'Other')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
