# Generated by Django 3.1.7 on 2021-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20210412_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Info Required'), (3, 'In Progress'), (4, 'Closed')], default=1, null=True),
        ),
    ]
