# Generated by Django 3.1.7 on 2021-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20210412_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Feature Request'), (2, 'Bug'), (3, 'Other')], default=2, null=True),
        ),
    ]
