# Generated by Django 3.1.7 on 2021-04-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticketcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='user',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='comment',
            new_name='message',
        ),
    ]
