# Generated by Django 3.1.7 on 2021-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210418_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unseen',
            field=models.BooleanField(default=False),
        ),
    ]
