# Generated by Django 3.1.7 on 2021-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210419_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Role Update'), (2, 'Ticket Assignment'), (3, 'Ticket Unassignment'), (4, 'Project Enrollment'), (5, 'Project Disenrollment'), (6, 'New Ticket Comment')], null=True),
        ),
    ]
