# Generated by Django 3.1.7 on 2021-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210419_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='unseen',
            field=models.BooleanField(default=True),
        ),
    ]
