# Generated by Django 3.1.7 on 2021-04-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210410_0750'),
        ('tickets', '0006_auto_20210418_0608'),
        ('notifications', '0007_auto_20210419_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='info_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='role_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer'), (2, 'Admin'), (3, 'Project Manager')], null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
