# Generated by Django 3.1.7 on 2021-04-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20210419_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ticket',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='default message', max_length=400),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Role Update'), (2, 'Ticket Assignment'), (3, 'Project Enrollment'), (4, 'New Ticket Comment')], null=True),
        ),
    ]
