# Generated by Django 3.1.7 on 2021-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20210419_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='pk_to_link',
            new_name='pk_for_link',
        ),
    ]
