# Generated by Django 3.1.7 on 2021-04-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210410_0750'),
        ('notifications', '0011_auto_20210419_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='pk_for_link',
        ),
        migrations.AddField(
            model_name='notification',
            name='new_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Developer'), (2, 'Admin'), (3, 'Project Manager')], null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
