name: Build and test django-bugtracker

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'

jobs:
  test:
    name: Run test suite in Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: 	docker-compose -f docker-compose.dev.yml build

      - name: Run tests
        run: make test
